import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import useSWR from "swr";
import { useEffect } from "react";
import Layout from "../components/layout";
import DadHatsPublic from "../components/DadHatsPublic";
import Loading from "../components/Loading";

export const GET_DAD_HATS = gql`
  query GetHats {
    getHats {
      data {
        name
        image
        _id
        owner {
          name
        }
      }
    }
  }
`;

const fetcher = (url) => fetch(url).then((r) => r.json());

export default function Home() {
  const { data: user, error: userError } = useSWR("/api/user", fetcher);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{user && <Data user={user} />}</main>
    </Layout>
  );
}

const Data = ({ user }) => {
  const { loading, error, data } = useQuery(GET_DAD_HATS, {
    variables: { id: user.id },
  });

  if (loading) return <Loading />;

  if (error) return <h1>{error.message}</h1>;

  return (
    <>
      <DadHatsPublic data={data} />

      {/* <pre>{JSON.stringify(data, null, 2)}</pre> */}
    </>
  );
};
